sudo: false
language: ruby

addons:
  code_climate:
    repo_token:
      secure: "joz+uCh0JrnDF25NyBO8X5do+HSn0DPcY+g7SnQBrqdg9UFj05UbasosuOdSHobDOr0lMM/CAc2Zdlti9n0E68kvicC11k+0aHAl3XeeBqfuDiXyC3Dn4kroLy1WXSBj238bVG8UDvWBf8mi2/QvXM7TRdBo83bwXZ+gBuos4IYmtWwu8nmQnN7X8zLSK++zOUSn+JFXPvZy9eHZFzlmuJeNl4Lb/1SOplZ8pS+DpWUuQARmrswEcetp3eW6Cd1Ad/Gzuyz25U7uu4O3JUyUiEXiJ6jAv/0/vZDaUGh7vBmHoBKuYgdGXcTjpUAlOM/JNRkxAF9QkBasR+r6AwAIUyeN5PYeYzpEywsid2FtF2lvMGvBUxhB1qs74wmbX32hwnMwq6SEy+nZmgvkEbS8N9J4B0QAMZU81Ke3b91GvrKPD8tTmaPchOKJ+ve+gQFVSaAq6Ti8V8SP2zh2yNcawIR1tvvDmF+lqZRcqJo8/2XNv5WCOqhSGoYm2FPxX2tCbv90/CYimq7rPFKCtymrf/KHrF6DiqcMFWIzKXeT4EFMdLEjDf2YodwhhS7B91zc+7ZDRjok1t/XbEsD+wMgEEQ4cug0hhhrELppQ8dQ+w8mXUbsSm6Xwv+BVXqn5bTBB5zuTJFBav7bhcyZexS6gBWw1W7RKnZbOozrNsQmWOg="

rvm:
  - 2.3.3
  - 2.4.1

before_install: gem install bundler -v 1.13.6

after_success:
  - bundle exec codeclimate-test-reporter
